### ISSUE TITLE
Display of colours

### ISSUE THREAD

**Issue by digitisingsafety** [robertmoro/7ColorEPaperPhotoFrame#1]
Has anyone had any issues with colours displaying incorrectly on the 5.65" 7-color e-paper using the code as-is?  I've ruled out the display.  Robert's own code works perfectly so I think my problem is either with the Waveshare library code, my Arduino or my bitmaps (although I followed the guide exactly on these).

**Comment by digitisingsafety** [comment]
By way of an update, I posted this on Arduino forum with images attached (https://forum.arduino.cc/t/waveshare-5-65-7-color-inverting-bitmap-colours/1038609)

**Comment by robertmoro** [comment]
Two things you can try:
1. Does the provided example bitmap file 'lenna.bmp' work for you?
2. The readme.md file explains how to create a seven color palette in Gimp. I guess you can fix your issue by moving those colors around in the palette, see if that makes a difference.

**Comment by digitisingsafety** [comment]
Lenna.bmp worked fine.

I'll try swapping the colours around in the palette and come back.

**Comment by digitisingsafety** [comment]
Update.  Swapping the colours in the palette didn't work.  Nor did duplicating the palette in Lenna.bmp (which were in a wholly different order).

**Comment by robertmoro** [comment]
If Lenna is displayed correctly, the issue must be in how you create the images. Do note that there is no palette information read from the bitmap file for displaying the images. Only the image array is read from the bitmap file. Each byte in the image array contains the information of two pixels, one color per nibble. in binary it looks like this:
0000 (0) - black,
0001 (1) - white
0010 (2) - green
0011 (3) - blue
0100 (4) - red
0101 (5) - yellow
0110 (6) - orange
I have uploaded single color bitmap images. You can check the information above by opening those files in a hex editor and start reading where the image array starts.

**Comment by digitisingsafety** [comment]
![myred](https://user-images.githubusercontent.com/75689865/194557878-f30f96aa-4bd9-459b-abf7-a3828ea34659.png)
![robred](https://user-images.githubusercontent.com/75689865/194557882-1cbf0de6-cde9-4083-8215-1535d9fb8cf4.png)
Thanks again for your assistance Robert.  I've done my own version of the red to test, and checking it in hex editor against yours, it looks completely different (mine top, yours under).  And that's following your instructions exactly.

Do you think it's my GIMP setup (I must admit I'm not normally a GIMP user).  Which version of GIMP are you using as your new screenshots in the readme look different to my own?

**Comment by digitisingsafety** [comment]
**Found the issue.**  Colormap.  I don't know if your version is ordering the colormap the same as the palette after indexing, but mine isn't, so after indexing the colormap needs rearranging.  I hope there's an automatic way to do this!

**Comment by robertmoro** [comment]
You are welcome, great to hear that it works now! I am using GIMP 2.10.30. I did not know about this colormap. Thanks for letting me know, I will update the documentation. Are you going to print the frame as well?

**Comment by digitisingsafety** [comment]
I hadn't thought of printing it.  I have a chunky MDF frame I was going to use (the plan is to have some mini solar panels in it to try and keep the battery topped up) but I'll see how I get on and report back!

**Comment by robertmoro** [comment]
I guess you have seen the link in the [BOM](https://github.com/robertmoro/7ColorEPaperPhotoFrame/blob/main/README.md#bom) to the 3D model of a frame I designed. Nice idea with the solar panels. Do note to keep the display itself out of direct sunlight.
